### ISSUE TITLE
PDF viewer displayed after download failure

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#373] opened 2021-11-04 07:12 UTC
1) Configure syncing for WebDAV
2) Try to download a file that's not available on the WebDAV server from the items list. The icon will change to the red circle and exclamation mark.
3) Tap (i).
4) Scroll down to Attachments
5) Tap the attachment with the (!) there. It will show "The attachment file could not be found." Tap Retry.

For me, instead of the download just failing again, two copies of the PDF viewer open up, and it says "Unable to Display Document". If I tap the back button, I'm in the second copy of the viewer.

The attachment then shows as downloaded (no (!)), and tapping it again shows the broken PDF viewer again.

**Comment by dstillman** [comment] 2021-11-04 08:09
Same thing happens with a webview for a snapshot

**Comment by michalrentka** [comment] 2021-11-08 09:59
I couldn't reproduce this, but I noticed one issue. At the very least it shouldn't open 2 windows now, but I think the whole issue should be fixed. It'll be up in next build.

**Closed** 2021-11-17 06:59 UTC
Labels: Bug
