### ISSUE TITLE
Ink annotation edges are sometimes chopped off

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#459] opened 2022-03-19 22:50 UTC
See the last "n" in https://github.com/zotero/zotero-ios/issues/458

**Comment by michalrentka** [comment] 2022-03-21 10:20
This seems to be a PSPDFKit issue, I'll follow up after talking to their support.

**Comment by michalrentka** [comment] 2022-03-22 07:41
PSPDFKit support confirmed it's their issue: `We have an internal ticket where we tracked down a similar issue to an edge case in Apple’s Core Graphics path rendering.`

I guess I can close this ticket as I can't do anything to fix this. Hopefully it will be fixed in future PSPDFKit updates.

**Comment by michalrentka** [comment] 2023-07-19 09:05
This should be fixed in 12.3.1

**Closed by michalrentka** 2023-07-19 09:05 UTC
Labels: Bug, 3rd Party
