### ISSUE TITLE
Tags on standalone notes

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#281] opened 2021-04-22 20:56 UTC
https://forums.zotero.org/discussion/89254/ios-ipad-standalone-notes

Similar to standalone notes in the client, we'll want some way to view and assign these.

I also think we could make the whole note popup bigger to give more room for writing, and then we'd have more room for a bottom toolbar or other chrome for this.

**Comment by michalrentka** [comment] 2021-04-23 09:04
Duplicate of #179

**Closed by michalrentka** 2021-04-23 09:04 UTC
Labels: Enhancement, P3
