### ISSUE TITLE
Startup crash: "Controllers: can't create UserControllers - Error Domain=io.realm Code=1 No such table exists"

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#538] opened 2022-08-23 15:45 UTC
https://forums.zotero.org/discussion/99256/error-message

**Comment by michalrentka** [comment] 2022-09-08 09:55
Can't reproduce this and the user deleted and re-installed the app, so the error is lost for now. This points to a corrupted database, which I'm not sure how this happened yet. Anyway I implemented better crash reporting and if anyone reports this issue again, we'll be able to get the database files from them and properly see what's going on. Closing this ticket since it's not reproducible.

**Closed by michalrentka** 2022-09-08 09:55 UTC
